baseURL = 'https://opbenesh.github.io/'
languageCode = 'en-us'
title = 'Ben Esh Presents: TIL in Blog Form'
theme = "PaperMod"

[outputs]
    home = ["HTML", "RSS", "JSON"]

[params.homeInfoParams]
    Title = "Ben Esh Presents: TIL in Blog Form ☢️"
    Content = "Product Manager by day, nostalgic ex-coder by night. This is a collection of things I learned, built, or broke while doom coding."

[[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/ben-esh"

[[params.socialIcons]]
    name = "email"
    url = "/contact"

[menu]
  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search"
    weight = 5
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 20
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact"
    weight = 30
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags"
    weight = 40
  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories"
    weight = 50
[params.assets]
    favicon = "favicon.png"
    apple_touch_icon = "apple-touch-icon.png"

[params]
    ShowShareButtons = true
    ShowReadingTime = true
    ShowPostNavLinks = true
    ShowBreadCrumbs = true
    author = "Ben Esh"

[related]
    includeNewer = true
    threshold = 80
    toLower = true
    [[related.indices]]
        name = "tags"
        weight = 100
    [[related.indices]]
        name = "categories"
        weight = 80
