baseURL = 'https://opbenesh.github.io/opbenesh-blog/'
languageCode = 'en-us'
title = 'Ben Esh Presents: TIL in Blog Form'
theme = "PaperMod"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/ben-esh"
